[build]
publish = "_site"
command = "npm run build"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/_site/index.html"
  status = 200

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = '''
        default-src 'self';
        style-src 'self' 'unsafe-inline';
        img-src 'self';
        script-src 'self' 'piwik.technologiestiftung-berlin.de';
        frame-ancestors 'self';
        base-uri 'self';
        connect-src 'self';
        form-action 'self'
    '''