[build]
publish = "_site"
command = "npm run build"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/_site/index.html"
  status = 200